INSERT INTO Servicio (nombre) VALUES ('Atención Ambulatoria');
INSERT INTO Servicio (nombre) VALUES ('Internación General');
INSERT INTO Servicio (nombre) VALUES ('Cirugía General');
INSERT INTO Servicio (nombre) VALUES ('Cirugía Cardiovascular');
INSERT INTO Servicio (nombre) VALUES ('Unidad de Terapia Intensiva');
INSERT INTO Servicio (nombre) VALUES ('Pediatría');
INSERT INTO Servicio (nombre) VALUES ('Ginecología y Obstetricia');
INSERT INTO Servicio (nombre) VALUES ('Laboratorio Clínico');
INSERT INTO Servicio (nombre) VALUES ('Radiología');
INSERT INTO Servicio (nombre) VALUES ('Tomografía Computada');
INSERT INTO Servicio (nombre) VALUES ('Resonancia Magnética');
INSERT INTO Servicio (nombre) VALUES ('Ecografía');
INSERT INTO Servicio (nombre) VALUES ('Banco de Sangre');
INSERT INTO Servicio (nombre) VALUES ('Emergencias');
INSERT INTO Servicio (nombre) VALUES ('Oncología');
INSERT INTO Servicio (nombre) VALUES ('Diálisis');
INSERT INTO Servicio (nombre) VALUES ('Farmacia Hospitalaria');
INSERT INTO Servicio (nombre) VALUES ('Rehabilitación');
INSERT INTO Servicio (nombre) VALUES ('Kinesiología');
INSERT INTO Servicio (nombre) VALUES ('Odontología');
INSERT INTO Servicio (nombre) VALUES ('Oftalmología');
INSERT INTO Servicio (nombre) VALUES ('Hemoterapia');
INSERT INTO Servicio (nombre) VALUES ('Endoscopía');
INSERT INTO Servicio (nombre) VALUES ('Nutrición Clínica');
INSERT INTO Servicio (nombre) VALUES ('Vacunatorio');
INSERT INTO Servicio (nombre) VALUES ('Salud Mental');
INSERT INTO Servicio (nombre) VALUES ('Psicología');
INSERT INTO Servicio (nombre) VALUES ('Neurología');
INSERT INTO Servicio (nombre) VALUES ('Dermatología');
INSERT INTO Servicio (nombre) VALUES ('Cardiología');
INSERT INTO Servicio (nombre) VALUES ('Neonatología');
INSERT INTO Servicio (nombre) VALUES ('Infectología');
INSERT INTO Servicio (nombre) VALUES ('Telemedicina');
INSERT INTO Servicio (nombre) VALUES ('Rondas Sanitarias');
INSERT INTO Servicio (nombre) VALUES ('Atención Domiciliaria');
INSERT INTO Servicio (nombre) VALUES ('Fisiatría');
INSERT INTO Servicio (nombre) VALUES ('Traumatología');