INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Centro Médico Roig', 1, 'Primer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Posta Sanitaria Casas', 2, 'Primer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Posta Sanitaria Trujillo', 2, 'Tercer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Posta Sanitaria Menendez', 3, 'Segundo Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Hospital Benítez', 3, 'Segundo Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Posta Sanitaria Llamas', 3, 'Segundo Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Hospital Izquierdo', 4, 'Segundo Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Posta Sanitaria Cases', 4, 'Tercer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Posta Sanitaria Cruz', 1, 'Tercer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Instituto Valbuena', 4, 'Primer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Hospital Priego', 5, 'Primer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Instituto Falcó', 6, 'Segundo Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Posta Sanitaria Palacio', 6, 'Segundo Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Hospital Cuevas', 7, 'Tercer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Centro Médico Mayol', 1, 'Tercer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Hospital Santos', 7, 'Segundo Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Posta Sanitaria Tur', 7, 'Segundo Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Unidad Sanitaria Lloret', 7, 'Tercer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Centro Médico Nogués', 8, 'Segundo Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Centro Médico Calvet', 8, 'Segundo Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Instituto Paz', 8, 'Segundo Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Hospital Bayón', 1, 'Primer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Clínica Palacio', 8, 'Tercer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Unidad Sanitaria Reyes', 9, 'Segundo Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Clínica Solsona', 9, 'Primer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Hospital Valbuena', 9, 'Tercer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Centro Médico Narváez', 10, 'Primer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Unidad Sanitaria Barceló', 10, 'Tercer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Centro Médico Pedrero', 2, 'Segundo Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Unidad Sanitaria Ramos', 10, 'Tercer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Centro Médico Belda', 11, 'Primer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Clínica Tejero', 11, 'Primer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Instituto Mendez', 11, 'Primer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Centro Médico Pinto', 12, 'Segundo Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Centro Médico Mayoral', 12, 'Tercer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Centro Médico Abellán', 13, 'Segundo Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Centro Médico Roma', 13, 'Segundo Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Centro Médico Ocaña', 14, 'Tercer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Unidad Sanitaria Luís', 15, 'Tercer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Centro Médico Pizarro', 15, 'Tercer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Centro Médico Arce', 15, 'Tercer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Unidad Sanitaria Ortiz', 16, 'Tercer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Unidad Sanitaria Jara', 16, 'Primer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Instituto Alcaraz', 16, 'Primer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Centro Médico Pujadas', 16, 'Primer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Hospital Cisneros', 17, 'Tercer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Instituto Raya', 17, 'Primer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Hospital Tejero', 17, 'Primer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Clínica Aragón', 17, 'Tercer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Hospital Sáenz', 17, 'Tercer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Posta Sanitaria Higueras', 18, 'Primer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Instituto Maldonado', 19, 'Tercer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Posta Sanitaria Alemán', 20, 'Segundo Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Clínica Carrasco', 20, 'Tercer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Instituto Pino', 20, 'Segundo Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Hospital Campos', 20, 'Primer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Posta Sanitaria Barrera', 21, 'Primer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Hospital Pallarès', 21, 'Segundo Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Unidad Sanitaria Carreras', 21, 'Primer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Clínica Valderrama', 21, 'Segundo Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Instituto Vargas', 21, 'Tercer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Instituto Pedrero', 22, 'Segundo Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Instituto Sanabria', 23, 'Primer Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Unidad Sanitaria Navarro', 23, 'Segundo Nivel');
INSERT INTO EfectorDeSalud (nombre, id_prov, nivel) VALUES ('Unidad Sanitaria Arnau', 24, 'Primer Nivel');
