INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Parra', 1, 'Provincial', 'Licencia','Gestiona', 'No genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Rosselló', 1, 'Proveedor', 'Licencia','No gestiona', 'Genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Pineda', 1, 'Provincial', 'Propio','No gestiona', 'Genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Ochoa', 2, 'Proveedor', 'Propio','No gestiona', 'Genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Blanco', 3, 'Provincial', 'Propio','Gestiona', 'No genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Carmona', 3, 'Proveedor', 'Licencia','Gestiona', 'Genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Plana', 3, 'Proveedor', 'Propio','Gestiona', 'Genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Moll', 4, 'Proveedor', 'Propio','No gestiona', 'Genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Nebot', 5, 'Provincial', 'Licencia','Gestiona', 'Genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Rubio', 5, 'Provincial', 'Propio','Gestiona', 'Genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Viña', 6, 'Provincial', 'Licencia','No gestiona', 'Genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Azorin', 6, 'Provincial', 'Licencia','No gestiona', 'Genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Royo', 6, 'Provincial', 'Propio','No gestiona', 'No genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Catalán', 7, 'Proveedor', 'Licencia','No gestiona', 'No genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Arana', 7, 'Provincial', 'Licencia','No gestiona', 'No genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Almeida', 8, 'Proveedor', 'Licencia','No gestiona', 'No genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Montesinos', 9, 'Proveedor', 'Licencia','No gestiona', 'No genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Castilla', 9, 'Proveedor', 'Propio','No gestiona', 'Genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Miró', 10, 'Provincial', 'Propio','Gestiona', 'Genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Sabater', 10, 'Provincial', 'Propio','No gestiona', 'Genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Rocamora', 11, 'Proveedor', 'Licencia','No gestiona', 'No genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Villena', 12, 'Provincial', 'Propio','No gestiona', 'No genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Plaza', 12, 'Proveedor', 'Propio','Gestiona', 'Genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Chaparro', 13, 'Proveedor', 'Licencia','Gestiona', 'No genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Azcona', 13, 'Provincial', 'Propio','No gestiona', 'Genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Alegria', 13, 'Provincial', 'Licencia','No gestiona', 'No genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Nicolás', 14, 'Provincial', 'Licencia','Gestiona', 'No genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Larrea', 14, 'Proveedor', 'Licencia','Gestiona', 'Genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Catalá', 15, 'Proveedor', 'Licencia','Gestiona', 'Genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Pinilla', 16, 'Provincial', 'Licencia','No gestiona', 'Genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Sebastián', 16, 'Proveedor', 'Licencia','Gestiona', 'No genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Pareja', 16, 'Provincial', 'Propio','Gestiona', 'Genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Montoya', 17, 'Proveedor', 'Propio','Gestiona', 'Genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Esparza', 18, 'Proveedor', 'Propio','No gestiona', 'No genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Morata', 18, 'Proveedor', 'Propio','Gestiona', 'No genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Vilar', 18, 'Proveedor', 'Licencia','Gestiona', 'No genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Alcázar', 19, 'Provincial', 'Licencia','Gestiona', 'No genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Falcó', 20, 'Provincial', 'Propio','No gestiona', 'No genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Jover', 20, 'Provincial', 'Licencia','Gestiona', 'No genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Cabezas', 20, 'Proveedor', 'Propio','No gestiona', 'Genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Blanca', 21, 'Proveedor', 'Propio','No gestiona', 'Genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Lobato', 21, 'Proveedor', 'Propio','No gestiona', 'No genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Casanovas', 22, 'Proveedor', 'Propio','Gestiona', 'Genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Ferrándiz', 22, 'Proveedor', 'Licencia','Gestiona', 'No genera');
INSERT INTO HCE (nombre, id_prov, tipo_gestion, tipo_desarrollo,gestion_estudios, generacion_receta_digital) VALUES ('HCE Valbuena', 23, 'Provincial', 'Licencia','Gestiona', 'Genera');
