INSERT INTO DocumentoDigital (nombre, tipo) VALUES ('Hemograma completo', 'Estudio de Laboratorio');
INSERT INTO DocumentoDigital (nombre, tipo) VALUES ('Análisis de orina', 'Estudio de Laboratorio');
INSERT INTO DocumentoDigital (nombre, tipo) VALUES ('Glucemia en ayunas', 'Estudio de Laboratorio');
INSERT INTO DocumentoDigital (nombre, tipo) VALUES ('Perfil lipídico', 'Estudio de Laboratorio');
INSERT INTO DocumentoDigital (nombre, tipo) VALUES ('Examen de HIV', 'Estudio de Laboratorio');
INSERT INTO DocumentoDigital (nombre, tipo) VALUES ('Creatinina sérica', 'Estudio de Laboratorio');
INSERT INTO DocumentoDigital (nombre, tipo) VALUES ('PCR', 'Estudio de Laboratorio');
INSERT INTO DocumentoDigital (nombre, tipo) VALUES ('Serología para Chagas', 'Estudio de Laboratorio');
INSERT INTO DocumentoDigital (nombre, tipo) VALUES ('Función hepática', 'Estudio de Laboratorio');
INSERT INTO DocumentoDigital (nombre, tipo) VALUES ('Urocultivo', 'Estudio de Laboratorio');
INSERT INTO DocumentoDigital (nombre, tipo) VALUES ('Electrocardiograma', 'Práctica Médica');
INSERT INTO DocumentoDigital (nombre, tipo) VALUES ('Radiografía de tórax', 'Práctica Médica');
INSERT INTO DocumentoDigital (nombre, tipo) VALUES ('Ecografía abdominal', 'Práctica Médica');
INSERT INTO DocumentoDigital (nombre, tipo) VALUES ('Colonoscopía', 'Práctica Médica');
INSERT INTO DocumentoDigital (nombre, tipo) VALUES ('Resonancia magnética cerebral', 'Práctica Médica');
INSERT INTO DocumentoDigital (nombre, tipo) VALUES ('Tomografía de tórax', 'Práctica Médica');
INSERT INTO DocumentoDigital (nombre, tipo) VALUES ('Biopsia de piel', 'Práctica Médica');
INSERT INTO DocumentoDigital (nombre, tipo) VALUES ('Mamografía', 'Práctica Médica');
INSERT INTO DocumentoDigital (nombre, tipo) VALUES ('Endoscopía digestiva alta', 'Práctica Médica');
INSERT INTO DocumentoDigital (nombre, tipo) VALUES ('Espirometría', 'Práctica Médica');